apiVersion: v2
name: infra
version: 1.0.0
type: application
dependencies:
  - name: traefik
    alias: traefik
    repository: "https://traefik.github.io/charts"
    version: 20.8.0
    condition: enabledComponents.traefik