enabledComponents:
  traefik: true

traefik:
  experimental:
    plugins:
      enabled: true
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
  service:
    annotations:
      load-balancer.hetzner.cloud/http-redirect-https: "false"
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/name: traefik
      load-balancer.hetzner.cloud/uses-proxyprotocol: "false"
      load-balancer.hetzner.cloud/use-private-ip: "true"